# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cd244641ebe064e6289ab0911615f683"
name = "商品インポート/エクスポート"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "app/scopes_update" ]
uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_online_store_navigation,read_products,write_files,write_inventory,write_online_store_navigation,write_products"

[auth]
redirect_urls = [ "https://example.com/auth/callback" ]
